### ISSUE TITLE
Error when running on Win 11 + Python 3.11

### ISSUE THREAD

**Issue by teeedubb** [philpennock/tv-sony#1]
Hi,

Thanks for putting the time into this script.

I have installed on windows 11 with python 3.11, and after installing some additional modules, I get the following error when attempting to pair the TV. 

`PS C:\Users\tw\Downloads\tv-sony-main> python.exe tv --register ironhide -H 192.168.123.202 -t sony-tv
PIN on screen> 5704
{
  "id": 1,
  "result": []
}

Traceback (most recent call last):
  File "C:\Users\tw\Downloads\tv-sony-main\tv", line 1804, in <module>
    rv = start()
         ^^^^^^^
  File "C:\Users\tw\Downloads\tv-sony-main\tv", line 1789, in _start
    def _start(): return _main(sys.argv[1:], argv0=argv0)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tw\Downloads\tv-sony-main\tv", line 1765, in _main
    remote.register_remote(
  File "C:\Users\tw\Downloads\tv-sony-main\tv", line 806, in register_remote
    self.config.persist_current(devicename)
  File "C:\Users\tw\Downloads\tv-sony-main\tv", line 324, in persist_current
    self.set_default_tv(write_name)
  File "C:\Users\tw\Downloads\tv-sony-main\tv", line 350, in set_default_tv
    src.symlink_to(dest.name)
  File "C:\Users\tw\AppData\Local\Programs\Python\Python311\Lib\pathlib.py", line 1198, in symlink_to
    os.symlink(target, self, target_is_directory)
OSError: [WinError 1314] A required privilege is not held by the client: 'sony-tv.hostname' -> 'C:\\Users\\tw\\.config\\tv\\default.hostname'`

After running the comman, the TV shows the pin, I input it into the console and thats when I get this error. The .config\tv directory exists, as does .cache\tv

**Comment by philpennock** [comment]
I don't use Windows, so am not sure, but it _appears_ that this is a problem with Windows raising errors when you try to create a symbolic link unless you're an administrator.

I don't like saying "run as administrator" because that's slightly scary, but ... you might need to run as administrator.  Sorry, I had no idea that a simple symlink would still cause problems today on Windows.

You might be able to avoid it by using the `--tv` option to specify an explicit name and avoid the "manage the symlinks for the default TV" logic.

**Comment by teeedubb** [comment]
Hey mate,

Ive tried a different approach - using WSL.
I had to install the module pygments, and still got an error, but after creating the folder/file it is now working

Thank you very much, this looks perfect for my needs of automating the TV.

Error here incase it is of interest:

/mnt/c/Users/law/tw/scripts/linux# ./tv --register ironhide -H 192.168.123.202 -t sony-tv
PIN on screen> 8743
{
  "id": 1,
  "result": []
}

Traceback (most recent call last):
  File "/mnt/c/Users/law/tw/scripts/linux/./tv", line 1804, in <module>
    rv = start()
  File "/mnt/c/Users/law/tw/scripts/linux/./tv", line 1789, in _start
    def _start(): return _main(sys.argv[1:], argv0=argv0)
  File "/mnt/c/Users/law/tw/scripts/linux/./tv", line 1765, in _main
    remote.register_remote(
  File "/mnt/c/Users/law/tw/scripts/linux/./tv", line 800, in register_remote
    self.config.auth_remotename_file.write_text(nickname + '\n')
  File "/usr/lib/python3.10/pathlib.py", line 1154, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/tv/sony-tv.remotename'
